name: ibkr_trade_mcp
description: Model Context Protocol (MCP) server for Interactive Brokers.
version: 0.1.0
publish_to: none
homepage: https://github.com/Aloshanai/ibkr_trade_mcp
repository: https://github.com/Aloshanai/ibkr_trade_mcp
issue_tracker: https://github.com/Aloshanai/ibkr_trade_mcp/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  json_rpc_2: ^3.0.2
  stream_channel: ^2.1.2
  ib_trade_core:
    path: ../ib_trade_core

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
